#!/bin/bash
set -e

export CPLUS_INCLUDE_PATH=$(python3 -c "import numpy; print(numpy.get_include())")

# Set GCC 9 for building
export CC=gcc-9
export CXX=g++-9

echo "🛠️  Using compiler: $CC / $CXX"

echo "🛠️  Building roi_align..."
cd models/AlphaPose/alphapose/utils/roi_align
python3 setup.py build_ext --inplace

echo "🛠️  Building deformable conv/pool (DCN)..."
cd ../../models/layers/dcn
python3 setup.py build_ext --inplace

echo "🛠️  Building NMS..."
cd ../../../../detector/nms

# The committed src/soft_nms_cpu.cpp was regenerated by Cython 3.1.2 (Sep 2025)
# which emits NumPy 2.x C-API accessors (PyDataType_ELSIZE, PyArray_MultiIter_NUMITER, ...)
# that do not exist in NumPy 1.24.x (which is what requirements.txt pins).
# Regenerate the .cpp from the .pyx using Cython 0.29.x — the last branch that
# targets the NumPy 1.x C API. Cython 0.29.37 supports Python 3.11.
echo "🛠️  Regenerating soft_nms_cpu.cpp from .pyx with Cython<3 (NumPy 1.x compatible)..."
pip install --no-cache-dir "Cython==0.29.37" >/dev/null
cython --cplus -3 src/soft_nms_cpu.pyx -o src/soft_nms_cpu.cpp

python3 setup.py build_ext --inplace

echo "✅ All extensions built successfully!"
