FROM nvidia/cuda:12.2.0-base-ubuntu20.04

RUN apt-get update && \
    apt-get install -y python3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY run_nvidia_dcgm.sh ./
RUN chmod +x run_nvidia_dcgm.sh

CMD ["/app/run_nvidia_dcgm.sh"]
