services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./videos:/videos
    environment:
      - MTX_PATHS_MYSTREAM_SOURCE=rtsp://127.0.0.1:8554/stream
      - MTX_PATHS_MYSTREAM_SOURCEONDEMAND=yes
      - MTX_RTSPADDRESS=:8554
      - MTX_HLSADDRESS=:8080
      - MTX_API=yes
      - MTX_APIADDRESS=:8081
      - MTX_RTMP=no
      - MTX_LOGLEVEL=debug

  ffmpeg-streamer:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: ffmpeg-streamer
    depends_on:
      mediamtx:
        condition: service_started
    volumes:
      - ./videos:/videos
    network_mode: host
    command: >
      -stream_loop -1
      -re
      -i /videos/rangeOfMotion/hd_00_00.mp4
      -c:v copy
      -an
      -f rtsp
      -rtsp_transport tcp
      rtsp://127.0.0.1:8554/stream
    restart: unless-stopped