# thanks to Paul DeCoursey (optimuspaul@github.com) for inspiration
# see: https://github.com/MVIG-SJTU/AlphaPose/issues/1057

FROM nvidia/cuda:12.1.0-devel-ubuntu20.04

RUN apt-get clean

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-change-held-packages \
    ffmpeg \
    git \
    build-essential \
    ninja-build \
    mesa-common-dev \
    libosmesa6 libosmesa6-dev \
    libgles2-mesa-dev \
    libglu1-mesa-dev \
    libyaml-dev \
    python3 python3-pip python3-tk \
    bc

ENV CUDA_HOME='/usr/local/cuda'

# Install PyTorch and torchvision for CUDA 12.1
RUN pip install --upgrade pip
RUN pip install torch==2.1.2+cu121 torchvision==0.16.2+cu121 torchaudio==2.1.2 --extra-index-url https://download.pytorch.org/whl/cu121

# Install OpenCV (headless for servers)
RUN pip install opencv-contrib-python-headless

RUN pip install numpy==1.23.5

RUN pip install cython

# Install other Python dependencies
RUN pip install cython_bbox==0.1.3 pycocotools six terminaltables scipy matplotlib visdom tqdm tensorboardx easydict pyyaml munkres timm==0.1.20 natsort boto3 gdown

# Clone AlphaPose and HalpeCOCOAPI
RUN mkdir /build
RUN cd /build && git clone https://github.com/HaoyiZhu/HalpeCOCOAPI.git
RUN cd /build && git clone https://github.com/MVIG-SJTU/AlphaPose.git

# Build HalpeCOCOAPI
RUN cd /build/HalpeCOCOAPI/PythonAPI && python3 setup.py build develop --user

WORKDIR /build/AlphaPose

# Build AlphaPose (with CUDA archs for common GPUs)
RUN TORCH_CUDA_ARCH_LIST="6.1;7.5;8.6" python3 setup.py build develop --user

# Download pretrained models (optional, or do this at runtime)
RUN python3 -c "import torchvision.models as tm; tm.resnet152(weights='IMAGENET1K_V2')"
RUN python3 -c "import torchvision.models as tm; tm.resnet50(weights='IMAGENET1K_V2')"

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 2

RUN mkdir -p detector/yolo/data && \
    gdown --id 1p6bi10UybpUIcq5D2XDsgQRLPJIr2RyI -O pretrained_models/fast_res50_256x192.pth && \
    gdown --id 1k-9cUGcdH5ZFN1NcMvZrO0ApW241tboD -O detector/yolo/data/yolov3-spp.weights

# Set entrypoint or CMD as needed
# CMD ["python3", "scripts/demo_inference.py", ...]