#!/bin/bash

echo "🎯 OpenVINO Environment Variables for 5.0 FPS"
echo "=============================================="
echo ""
echo "These are the environment variables that achieved 5.0 FPS:"
echo ""
echo "export OV_MODE=latency"
echo "export OV_STREAMS=1" 
echo "export OV_THREADS=7"
echo ""
echo "Additional variables that were set:"
echo "export OV_CPU_PINNING=false"
echo "export OV_HYPER_THREADING=false"
echo "export OV_BATCH_SIZE=1"
echo ""
echo "To apply these settings:"
echo "source <(echo 'export OV_MODE=latency; export OV_STREAMS=1; export OV_THREADS=7; export OV_CPU_PINNING=false; export OV_HYPER_THREADING=false; export OV_BATCH_SIZE=1')"
echo ""
echo "Performance achieved with these settings:"
echo "- Inference time: ~200ms (5.0 FPS)"
echo "- CPU usage: ~340% (7 threads)"
echo "- Memory pattern: latency-optimized"
