FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    mpv \
  && rm -rf /var/lib/apt/lists/*

COPY mpv-entrypoint.sh /usr/local/bin/mpv-entrypoint.sh
RUN chmod +x /usr/local/bin/mpv-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/mpv-entrypoint.sh"]
