version: '3.8'  # Updated version for better feature support

services:
  iperf-server:
    image: networkstatic/iperf3
    command: iperf3 -s
    ports:
      - "5201:5201"
    networks:
      test-network:
        ipv4_address: 172.28.1.2
    healthcheck:
      test: ["CMD", "iperf3", "-s", "--version"]
      interval: 2s
      timeout: 2s
      retries: 10

  iperf-client:
    image: networkstatic/iperf3
    command: iperf3 -c iperf-server -t 300 -i 0.1 -f m
    depends_on:
      iperf-server:
        condition: service_healthy  # Wait until server is ready
    networks:
      test-network:
        ipv4_address: 172.28.1.3

  tcpdump:
    image: nicolaka/netshoot
    command: tcpdump -i any -w /pcap/traffic.pcap -n -U -s 0 -nn port 5201
    volumes:
      - ./pcap:/pcap
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      test-network:
        ipv4_address: 172.28.1.5

  bpftrace:
    image: quay.io/iovisor/bpftrace:latest
    privileged: true
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug
      - ./capture_traffic.bt:/app/capture_traffic.bt
      - ./output:/output
    command: ["/bin/sh", "-c", "bpftrace /app/capture_traffic.bt > /output/traffic_data.txt"]
    networks:
      test-network:
        ipv4_address: 172.28.1.6

networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24